#!/usr/bin/env perl

use strict;
use warnings;

use lib "lib";
use Pear::LocalLoop::Algorithm::Main;

#More error checking could be added. but as it will only use the data generated by the script it should be ok.

my $file = $ARGV[0] or die "Input a CSV file.\n";

my $dbi = Pear::LocalLoop::Algorithm::Main->dbi();
$dbi->do("DELETE FROM OriginalTransactions");

$dbi = Pear::LocalLoop::Algorithm::Main->dbi();
my $insertStatement = $dbi->prepare("INSERT INTO OriginalTransactions (TransactionId, FromUserId, ToUserId, Value) VALUES (?, ?, ?, ?)");

$dbi->{AutoCommit} = 0;

open(my $data, '<', $file);

my $count = 1;
while (my $line = <$data>) {
  print "$count\n";
  
  chomp $line;
  my @columns = split("," , $line);
  $insertStatement->execute($columns[0],$columns[1],$columns[2],$columns[3]);
  
  $count++;
}

$dbi->commit();

close($file);

